const DEMO_KEY='kia-ora-client-hub-demo-v3';
const cfg=window.CLIENT_HUB_CONFIG||{};
const state={view:'dashboard',selectedClientId:null,search:'',clients:[],tasks:[],notes:[],meetings:[],user:null,mode:'demo',authMode:'signin'};
const demo={
 clients:[
  {id:'c1',name:'Ngāti Whākau',company:'Ngāti Whākau Iwi Trust',email:'contact@ngatiwhakau.iwi.nz',phone:'+64 27 555 1234',status:'Active',tags:['Important','Partner','Iwi'],notes:'Strong relationship partner focused on cultural preservation, economic development and community wellbeing.',last_contact_date:'2026-08-10',next_follow_up_date:'2026-08-18'},
  {id:'c2',name:'Aotearoa LTD',company:'Aotearoa LTD',email:'hello@aotearoa.example',phone:'+64 21 444 8811',status:'Active',tags:['Quarterly'],notes:'Quarterly review and contract management.',last_contact_date:'2026-08-08',next_follow_up_date:'2026-08-20'},
  {id:'c3',name:'Te Mana Group',company:'Te Mana Group',email:'aroha@temana.example',phone:'+64 22 333 1100',status:'Prospect',tags:['Proposal'],notes:'Proposal in progress; next step is scope confirmation.',last_contact_date:'2026-08-06',next_follow_up_date:'2026-08-16'},
  {id:'c4',name:'Rangitāne Holdings',company:'Rangitāne Holdings',email:'finance@rangitane.example',phone:'+64 27 221 7700',status:'Active',tags:['Finance'],notes:'Renewal and reporting relationship.',last_contact_date:'2026-08-05',next_follow_up_date:'2026-08-22'},
  {id:'c5',name:'Kōkiri Consulting',company:'Kōkiri Consulting',email:'team@kokiri.example',phone:'+64 20 981 4412',status:'Prospect',tags:['New'],notes:'New introduction; discovery meeting scheduled.',last_contact_date:'2026-08-04',next_follow_up_date:'2026-08-25'},
  {id:'c6',name:'Wīremu Tangiora',company:'Digital Transformation',email:'wiremu@example.nz',phone:'+64 21 991 840',status:'Active',tags:['Key Contact'],notes:'Digital transformation programme lead.',last_contact_date:'2026-08-09',next_follow_up_date:'2026-08-15'}],
 tasks:[
  {id:'t1',title:'Follow up with Wīremu',due_date:'2026-08-11',completed:false,client_id:'c6'},
  {id:'t2',title:'Prepare proposal',due_date:'2026-08-11',completed:true,client_id:'c3'},
  {id:'t3',title:'Send contract to Aotearoa LTD',due_date:'2026-08-12',completed:false,client_id:'c2'},
  {id:'t4',title:'Check in with Te Mana Group',due_date:'2026-08-16',completed:false,client_id:'c3'},
  {id:'t5',title:'Quarterly report',due_date:'2026-08-18',completed:false,client_id:'c4'}],
 notes:[
  {id:'n1',client_id:'c1',body:'Discussed new project scope and timeline.',created_at:'2026-08-10T10:00:00'},
  {id:'n2',client_id:'c3',body:'Proposal is ready for internal review.',created_at:'2026-08-09T13:00:00'},
  {id:'n3',client_id:'c6',body:'Requested a concise transformation summary.',created_at:'2026-08-09T08:00:00'}],
 meetings:[
  {id:'m1',client_id:'c1',title:'Project Kickoff – Ngāti Whākau',start:'2026-08-11T09:00:00+12:00',location:'Zoom Meeting'},
  {id:'m2',client_id:'c2',title:'Quarterly Review – Aotearoa LTD',start:'2026-08-11T11:00:00+12:00',location:'Boardroom'},
  {id:'m3',client_id:'c3',title:'Strategy Session – Te Mana Group',start:'2026-08-11T14:00:00+12:00',location:'Microsoft Teams'}]
};
let supabase=null;
if(window.supabase && cfg.supabaseUrl && cfg.supabaseAnonKey){supabase=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);}
const appEl=()=>document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=x=>JSON.parse(JSON.stringify(x));
const today=()=>new Date().toISOString().slice(0,10);
const client=id=>state.clients.find(c=>c.id===id);
const initials=n=>String(n||'').split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase();
const fmtDate=v=>v?new Date(v).toLocaleDateString('en-NZ',{day:'2-digit',month:'short',year:'numeric'}):'—';
const timeOnly=v=>v?new Date(v).toLocaleTimeString('en-NZ',{hour:'numeric',minute:'2-digit'}):'';
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.remove('hidden');clearTimeout(window._toast);window._toast=setTimeout(()=>el.classList.add('hidden'),2400)}
function saveLocal(){localStorage.setItem(DEMO_KEY,JSON.stringify({clients:state.clients,tasks:state.tasks,notes:state.notes,meetings:state.meetings}));}
function loadLocal(){const raw=localStorage.getItem(DEMO_KEY);if(raw){try{Object.assign(state,JSON.parse(raw));return true}catch{}}Object.assign(state,clone(demo));saveLocal();return false;}
async function loadCloud(){
 const [{data:clients,error:cErr},{data:tasks,error:tErr},{data:notes,error:nErr}]=await Promise.all([
  supabase.from('clients').select('*').order('name'),supabase.from('tasks').select('*').order('due_date',{ascending:true}),supabase.from('notes').select('*').order('created_at',{ascending:false})
 ]);
 if(cErr) throw cErr;if(tErr) throw tErr;if(nErr) throw nErr;
 state.clients=clients||[];state.tasks=tasks||[];state.notes=notes||[];state.meetings=[];
}
async function initAuth(){
 if(!supabase){state.mode='demo';loadLocal();return;}
 const {data}=await supabase.auth.getUser();
 if(data.user){state.user=data.user;state.mode='cloud';await loadCloud();}
 else {state.mode='demo';loadLocal();}
 supabase.auth.onAuthStateChange(async(_event,session)=>{
  state.user=session?.user||null;state.mode=state.user?'cloud':'demo';
  try{state.user?await loadCloud():loadLocal();}catch(e){toast('Could not load cloud data');loadLocal();}
  syncProfile();render();
 });
}
function syncProfile(){document.getElementById('profileName').textContent=state.user?.email?.split('@')[0]||'Hemi Brown';document.getElementById('profileMode').textContent=state.mode==='cloud'?'Cloud data':'Demo mode';}
function setView(v){state.view=v;state.selectedClientId=null;document.getElementById('sidebar').classList.remove('open');render();window.scrollTo({top:0,behavior:'smooth'})}
function navWire(){document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.getElementById('menuBtn').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));document.getElementById('globalSearch').addEventListener('input',e=>{state.search=e.target.value.trim().toLowerCase();render()});document.getElementById('topClientBtn').addEventListener('click',()=>openClientModal());document.getElementById('authBtn').addEventListener('click',openAuth);document.getElementById('topAuthBtn').addEventListener('click',openAuth);}
function header(title,sub,action=''){return `<div class="page-header"><div><div class="eyebrow">KIA ORA CLIENT HUB</div><h1>${esc(title)}</h1><p>${esc(sub)}</p></div><div class="page-actions">${action}</div></div>`}
function metric(icon,title,value,sub,accent='blue'){return `<div class="metric-card ${accent}"><div class="metric-icon">${icon}</div><div><div class="metric-title">${esc(title)}</div><div class="metric-value">${esc(value)}</div><div class="metric-sub">${esc(sub)}</div></div></div>`}
function panel(title,body,action=''){return `<section class="panel"><div class="panel-head"><h2>${esc(title)}</h2>${action||''}</div><div class="panel-body">${body}</div></section>`}
function taskRow(t){const c=client(t.client_id);return `<div class="task-row"><input type="checkbox" ${t.completed?'checked':''} data-task="${t.id}"><div class="task-main"><strong class="${t.completed?'done':''}">${esc(t.title)}</strong><span>${esc(c?.name||'')}</span></div><div class="task-due ${t.due_date===today()&&!t.completed?'today':''}">${t.completed?'Done':(t.due_date===today()?'Today':fmtDate(t.due_date))}</div></div>`}
function meetingRow(m){const c=client(m.client_id);return `<div class="meeting-row"><div class="meeting-time"><strong>${timeOnly(m.start)}</strong><span>${fmtDate(m.start)}</span></div><div class="meeting-main"><strong>${esc(m.title)}</strong><span>${esc(m.location||'')}</span><small>${esc(c?.name||'')}</small></div><div class="avatar-dot">${initials(c?.name||'C')}</div></div>`}
function recentNoteRow(n){return `<div class="activity-row"><div class="activity-icon note">▤</div><div><strong>${esc(client(n.client_id)?.name||'Client')}</strong><p>${esc(n.body)}</p></div><small>${fmtDate(n.created_at)}</small></div>`}
function render(){syncProfile();document.querySelectorAll('.side-nav,.mobile-nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));switch(state.view){case'dashboard':renderDashboard();break;case'clients':renderClients();break;case'calendar':renderCalendar();break;case'tasks':renderTasks();break;case'notes':renderNotes();break;case'settings':renderSettings();break;default:renderDashboard();}}
function renderDashboard(){
 const due=state.tasks.filter(t=>!t.completed&&t.due_date<=today()).length;const meetings=state.meetings.filter(m=>String(m.start).slice(0,10)===today()).length;const follow=state.clients.filter(c=>c.next_follow_up_date&&c.next_follow_up_date<=today()).length;
 const q=state.search;
 const filtered=state.clients.filter(c=>!q||[c.name,c.company,c.email,c.phone,(c.tags||[]).join(' '),c.notes].join(' ').toLowerCase().includes(q));
 appEl().innerHTML=`${header('Kia ora, Hemi 👋','Here’s what’s happening with your clients today.','<button class="btn primary" id="dashAdd">＋ Add Client</button>')}
 <div class="metric-grid">${metric('♙','Total Clients',state.clients.length,`${state.clients.length?'+ '+Math.min(state.clients.length,12):0} active relationships`,'blue')}${metric('✓','Follow Ups',follow,due?'Due now':'All on track','green')}${metric('□','Today’s Meetings',meetings,'View calendar','purple')}${metric('✉','Open Tasks',due,due?'Need attention':'Nothing due','orange')}</div>
 <div class="dashboard-grid top-grid">${panel('Upcoming Meetings',state.meetings.map(meetingRow).join('')||'<div class="empty">No meetings yet.</div>','<button class="panel-link" data-view="calendar">View Calendar</button>')}${panel('My Tasks',state.tasks.slice(0,5).map(taskRow).join('')||'<div class="empty">No tasks yet.</div>','<button class="panel-link" data-view="tasks">View All</button>')}${panel('Recent Activity',state.notes.slice(0,4).map(recentNoteRow).join('')||'<div class="empty">No notes yet.</div>','<button class="panel-link" data-view="notes">View All</button>')}</div>
 <div class="dashboard-grid lower-grid">${panel('Clients Needing Follow Up',state.clients.filter(c=>c.next_follow_up_date).slice(0,4).map(c=>`<div class="follow-row"><div class="avatar-dot dark">${initials(c.name)}</div><div><strong>${esc(c.name)}</strong><span>Last contact ${fmtDate(c.last_contact_date)}</span></div><strong class="due-date">${fmtDate(c.next_follow_up_date)}</strong></div>`).join('')||'<div class="empty">No follow-ups scheduled.</div>','<button class="panel-link" data-view="clients">View All</button>')}${panel('Quick Search',`<div class="search-card"><div class="search-big">${filtered.length}</div><div><strong>${q?`results for “${esc(q)}”`:'clients ready to work with'}</strong><span>Use the search box above to find clients, notes or tasks.</span></div></div><div class="quick-actions"><button class="btn secondary" id="dashAddNote">＋ Add Note</button><button class="btn secondary" id="dashAddTask">＋ Add Task</button></div>`,'')}</div>
 <section class="featured-client"><div class="featured-main"><div class="client-avatar large">${initials(state.clients[0]?.name||'NW')}</div><div><div class="client-label">FEATURED CLIENT</div><h2>${esc(state.clients[0]?.name||'Ngāti Whākau')} <span class="star">★</span></h2><p>${esc(state.clients[0]?.notes||'Your relationship overview will appear here.')}</p><div class="chips">${(state.clients[0]?.tags||['Important','Partner','Iwi']).map(t=>`<span class="chip">${esc(t)}</span>`).join('')}</div></div></div><div class="featured-meta"><div><span>Last Contact</span><strong>${fmtDate(state.clients[0]?.last_contact_date)}</strong></div><div><span>Next Follow Up</span><strong>${fmtDate(state.clients[0]?.next_follow_up_date)}</strong></div><button class="btn primary" id="featuredOpen">View Client</button></div><div class="tab-strip"><button class="tab active">Overview</button><button class="tab">Activity Timeline</button><button class="tab">Emails</button><button class="tab">Meetings</button><button class="tab">Notes</button><button class="tab">Tasks</button><button class="tab">Files</button><button class="tab">Details</button></div></section>`;
 document.getElementById('dashAdd')?.addEventListener('click',openClientModal);document.getElementById('dashAddNote')?.addEventListener('click',()=>openNoteModal());document.getElementById('dashAddTask')?.addEventListener('click',()=>openTaskModal());document.getElementById('featuredOpen')?.addEventListener('click',()=>{state.view='clients';state.selectedClientId=state.clients[0]?.id||null;renderClients()});navWire();
}
function renderClients(){
 if(state.selectedClientId){renderClientDetail();return;}
 const q=state.search;const list=state.clients.filter(c=>!q||[c.name,c.company,c.email,c.phone,(c.tags||[]).join(' '),c.notes].join(' ').toLowerCase().includes(q));
 appEl().innerHTML=`${header('Iwi / Clients','Manage your relationships, contacts and next steps.','<button class="btn primary" id="addClientBtn">＋ Add Client</button>')}<div class="toolbar"><div class="result-count">${list.length} client${list.length===1?'':'s'}</div><div class="view-toggle"><button class="active">Cards</button><button>List</button></div></div><div class="client-grid">${list.map(c=>`<article class="client-card"><div class="client-card-top"><div class="client-avatar">${initials(c.name)}</div><span class="status-pill ${c.status.toLowerCase().replace(/\s/g,'-')}">${esc(c.status)}</span></div><h3>${esc(c.name)}</h3><p class="company">${esc(c.company||'')}</p><p class="client-email">${esc(c.email||'No email')}</p><div class="chips">${(c.tags||[]).slice(0,3).map(t=>`<span class="chip">${esc(t)}</span>`).join('')}</div><div class="client-card-foot"><span>Follow up <strong>${fmtDate(c.next_follow_up_date)}</strong></span><div><button class="text-btn" data-open-client="${c.id}">View</button><button class="icon-btn" data-edit-client="${c.id}">✎</button></div></div></article>`).join('')||'<div class="empty full">No clients found.</div>'}</div>`;
 document.getElementById('addClientBtn').onclick=openClientModal;document.querySelectorAll('[data-open-client]').forEach(b=>b.onclick=()=>{state.selectedClientId=b.dataset.openClient;renderClients()});document.querySelectorAll('[data-edit-client]').forEach(b=>b.onclick=()=>openClientModal(b.dataset.editClient));
}
function renderClientDetail(){const c=client(state.selectedClientId);if(!c){state.selectedClientId=null;return renderClients()}const tasks=state.tasks.filter(t=>t.client_id===c.id);const notes=state.notes.filter(n=>n.client_id===c.id);appEl().innerHTML=`${header(c.name,c.company||'Client profile',`<button class="btn secondary" id="backClients">← Clients</button><button class="btn secondary" id="editSelected">Edit</button><button class="btn primary" id="addSelectedNote">＋ Note</button>`)}<section class="client-hero"><div class="client-hero-main"><div class="client-avatar xl">${initials(c.name)}</div><div><div class="eyebrow">${esc(c.status)}</div><h2>${esc(c.name)}</h2><p>${esc(c.notes||'No notes yet.')}</p><div class="chips">${(c.tags||[]).map(t=>`<span class="chip">${esc(t)}</span>`).join('')}</div></div></div><div class="contact-actions"><a class="btn secondary" href="mailto:${encodeURIComponent(c.email||'')}">✉ Email</a><a class="btn secondary" href="tel:${encodeURIComponent(c.phone||'')}">☎ Call</a></div></section><div class="dashboard-grid lower-grid"><div>${panel('Activity Timeline',notes.map(recentNoteRow).join('')||'<div class="empty">No notes yet.</div>')}</div><div>${panel('Tasks',tasks.map(taskRow).join('')||'<div class="empty">No tasks for this client.</div>','<button class="panel-link" id="addClientTask">＋ Add Task</button>')}</div></div><section class="info-strip"><div><span>Email</span><strong>${esc(c.email||'—')}</strong></div><div><span>Phone</span><strong>${esc(c.phone||'—')}</strong></div><div><span>Last Contact</span><strong>${fmtDate(c.last_contact_date)}</strong></div><div><span>Next Follow Up</span><strong>${fmtDate(c.next_follow_up_date)}</strong></div></section>`;document.getElementById('backClients').onclick=()=>{state.selectedClientId=null;renderClients()};document.getElementById('editSelected').onclick=()=>openClientModal(c.id);document.getElementById('addSelectedNote').onclick=()=>openNoteModal(c.id);document.getElementById('addClientTask')?.addEventListener('click',()=>openTaskModal(c.id));wireTasks();}
function renderTasks(){appEl().innerHTML=`${header('My Tasks','Keep follow-ups and commitments visible.','<button class="btn primary" id="newTaskBtn">＋ New Task</button>')}<div class="panel">${state.tasks.map(taskRow).join('')||'<div class="empty">No tasks yet.</div>'}</div>`;document.getElementById('newTaskBtn').onclick=()=>openTaskModal();wireTasks()}
function renderNotes(){appEl().innerHTML=`${header('Notes','Client context that should never get lost.','<button class="btn primary" id="newNoteBtn">＋ New Note</button>')}<div class="panel">${state.notes.map(recentNoteRow).join('')||'<div class="empty">No notes yet.</div>'}</div>`;document.getElementById('newNoteBtn').onclick=()=>openNoteModal()}
function renderCalendar(){appEl().innerHTML=`${header('Calendar','Your meetings and client catch-ups.','<button class="btn primary" id="addMeetingBtn">＋ Add Meeting</button>')}<div class="panel"><div class="calendar-list">${state.meetings.map(meetingRow).join('')||'<div class="empty">No meetings yet.</div>'}</div></div>`;document.getElementById('addMeetingBtn').onclick=()=>toast('Calendar connections come next — the meeting workspace is ready.')}
function renderSettings(){appEl().innerHTML=`${header('Settings','Connect the tools that power your client workspace.','')}<div class="settings-grid"><section class="setting-card"><h2>Account</h2><p class="row-meta">${state.user?`Signed in as ${esc(state.user.email)}`:'You are currently using Demo Mode.'}</p><div class="setting-actions"><button class="btn secondary" id="settingsAuth">${state.user?'Sign out':'Sign in'}</button>${!state.user?'<button class="btn secondary" id="settingsDemo">Reset Demo Data</button>':''}</div></section><section class="setting-card"><h2>Cloud storage</h2><div class="notice ${supabase?'success':''}"><strong>${supabase?'Supabase is configured':'Demo Mode is active'}</strong><br>${supabase?'Create an account and your client data can be stored in the cloud with Row Level Security.':'Add your Supabase URL and anon key in config.js to enable real accounts and cloud client data.'}</div></section><section class="setting-card"><h2>Next integrations</h2><div class="integration-row"><div><strong>Google Workspace</strong><span>Gmail + Google Calendar</span></div><button class="btn secondary" onclick="toast('Google integration is staged for the next step.')">Connect</button></div><div class="integration-row"><div><strong>Microsoft 365</strong><span>Outlook + Calendar</span></div><button class="btn secondary" onclick="toast('Microsoft integration is staged for the next step.')">Connect</button></div></section></div>`;document.getElementById('settingsAuth').onclick=openAuth;if(document.getElementById('settingsDemo'))document.getElementById('settingsDemo').onclick=()=>{localStorage.removeItem(DEMO_KEY);loadLocal();toast('Demo data reset');render()}}
function wireTasks(){document.querySelectorAll('[data-task]').forEach(b=>b.onchange=()=>toggleTask(b.dataset.task,b.checked))}
async function toggleTask(id,completed){const t=state.tasks.find(x=>x.id===id);if(!t)return;t.completed=completed;try{if(state.mode==='cloud')await supabase.from('tasks').update({completed}).eq('id',id);else saveLocal();render();}catch(e){toast('Could not save task')}
}
function openClientModal(id=null){const modal=document.getElementById('modal'),form=document.getElementById('clientForm');form.reset();document.getElementById('modalTitle').textContent=id?'Edit client':'Add client';const c=id?client(id):null;if(c){form.elements.id.value=c.id;form.elements.name.value=c.name;form.elements.company.value=c.company||'';form.elements.email.value=c.email||'';form.elements.phone.value=c.phone||'';form.elements.status.value=c.status||'Active';form.elements.tags.value=(c.tags||[]).join(', ');form.elements.notes.value=c.notes||'';}modal.classList.remove('hidden')}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
async function saveClient(e){e.preventDefault();const f=new FormData(e.target);const id=f.get('id');const item={name:f.get('name').trim(),company:f.get('company').trim(),email:f.get('email').trim(),phone:f.get('phone').trim(),status:f.get('status'),tags:String(f.get('tags')||'').split(',').map(s=>s.trim()).filter(Boolean),notes:f.get('notes').trim(),last_contact_date:today(),next_follow_up_date:today()};try{if(state.mode==='cloud'){if(id){await supabase.from('clients').update(item).eq('id',id)}else{const {data}=await supabase.from('clients').insert({...item,user_id:state.user.id}).select().single();item.id=data.id}}else{if(id)item.id=id;else item.id='local-'+Date.now();if(id)state.clients=state.clients.map(c=>c.id===id?{...c,...item}:c);else state.clients.unshift(item);saveLocal()}if(state.mode==='cloud')await loadCloud();closeModal();toast(id?'Client updated':'Client added');state.view='clients';render();}catch(err){toast('Could not save client')}
}
function openNoteModal(clientId=state.selectedClientId){const body=prompt('Add a note for '+(client(clientId)?.name||'this client'));if(!body)return;const item={id:'local-'+Date.now(),client_id:clientId,body,created_at:new Date().toISOString()};if(state.mode==='cloud'){supabase.from('notes').insert({...item,user_id:state.user.id}).then(({error})=>{if(error)return toast('Could not save note');state.notes.unshift(item);toast('Note added');render()});}else{state.notes.unshift(item);saveLocal();toast('Note added');render()}}
function openTaskModal(clientId=state.selectedClientId){const title=prompt('Task title');if(!title)return;const due=prompt('Due date (YYYY-MM-DD)',today())||today();const item={id:'local-'+Date.now(),client_id:clientId,title,due_date:due,completed:false};if(state.mode==='cloud'){supabase.from('tasks').insert({...item,user_id:state.user.id}).then(async({error})=>{if(error)return toast('Could not save task');await loadCloud();toast('Task added');render()});}else{state.tasks.unshift(item);saveLocal();toast('Task added');render()}}
function openAuth(){if(state.user){if(confirm('Sign out of Client Hub?'))supabase?.auth.signOut();return;}document.getElementById('authModal').classList.remove('hidden')}
function closeAuth(){document.getElementById('authModal').classList.add('hidden')}
async function authSubmit(e){e.preventDefault();if(!supabase){toast('Add Supabase settings to enable sign-in');return;}const f=new FormData(e.target);const email=f.get('email');const password=f.get('password');const fn=state.authMode==='signup'?supabase.auth.signUp.bind(supabase.auth):supabase.auth.signInWithPassword.bind(supabase.auth);const {error}=await fn({email,password});if(error){toast(error.message);return;}closeAuth();toast(state.authMode==='signup'?'Account created':'Signed in')}
function switchAuthMode(){state.authMode=state.authMode==='signin'?'signup':'signin';document.getElementById('authTitle').textContent=state.authMode==='signup'?'Create your Client Hub account':'Sign in to Client Hub';document.getElementById('signupBtn').textContent=state.authMode==='signup'?'Back to sign in':'Create account instead'}
document.querySelectorAll('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModal));document.querySelectorAll('[data-close-auth]').forEach(x=>x.addEventListener('click',closeAuth));document.getElementById('clientForm').addEventListener('submit',saveClient);document.getElementById('authForm').addEventListener('submit',authSubmit);document.getElementById('signupBtn').addEventListener('click',switchAuthMode);document.getElementById('demoModeBtn').addEventListener('click',()=>{state.user=null;state.mode='demo';loadLocal();closeAuth();toast('Demo mode enabled');render()});
(async function(){navWire();await initAuth();render();})();
